server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/koyla?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
